#!/usr/bin/env bash
# SIGIL Metrics Dashboard — 프로젝트 간 메트릭 대시보드
# Usage: bash scripts/sigil-metrics.sh [project]
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORKSPACE="$SCRIPT_DIR/.."

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

source "$SCRIPT_DIR/json-get.sh"

WS_JSON="$WORKSPACE/sigil-workspace.json"

if [ ! -f "$WS_JSON" ]; then
  echo -e "${RED}Error: sigil-workspace.json not found${NC}"
  exit 1
fi

PRODUCT_DIR="$(json_get "$WS_JSON" "folderMap.product")"
OUTPUT_DIR="$WORKSPACE/docs/reviews"
OUTPUT_FILE="$OUTPUT_DIR/$(date +%Y-%m-%d)-sigil-metrics.md"

TARGET_PROJECT="${1:-}"

mkdir -p "$OUTPUT_DIR"

# 날짜 차이 계산 (days)
date_diff() {
  local d1="$1" d2="$2"
  local s1 s2
  s1=$(date -d "$d1" +%s 2>/dev/null || echo "0")
  s2=$(date -d "$d2" +%s 2>/dev/null || echo "0")
  if [ "$s1" -eq 0 ] || [ "$s2" -eq 0 ]; then
    echo "-"
  else
    echo $(( (s2 - s1) / 86400 ))
  fi
}

# gate-log.md에서 Stage별 PASS 날짜 추출
extract_gate_date() {
  local gate_log="$1" stage="$2"
  grep -E "^\| *$stage *\|.*PASS" "$gate_log" 2>/dev/null \
    | grep -oE "[0-9]{4}-[0-9]{2}-[0-9]{2}" | head -1 || echo ""
}

{
  echo "# SIGIL 프로젝트 메트릭 대시보드"
  echo ""
  echo "> 생성일: $(date +%Y-%m-%d)"
  echo ""

  # --- Stage 소요일 비교 ---
  echo "## Stage 소요일 비교"
  echo ""
  echo "| Project | S1→S2 | S2→S3 | S3→S4 | 총 소요일 |"
  echo "|---------|:-----:|:-----:|:-----:|:---------:|"

  for proj_dir in "$WORKSPACE/$PRODUCT_DIR"/*/; do
    [ ! -d "$proj_dir" ] && continue
    proj_name="$(basename "$proj_dir")"
    [ -n "$TARGET_PROJECT" ] && [ "$proj_name" != "$TARGET_PROJECT" ] && continue

    gate_log="$proj_dir/gate-log.md"
    [ ! -f "$gate_log" ] && continue

    d1=$(extract_gate_date "$gate_log" "S1")
    d2=$(extract_gate_date "$gate_log" "S2")
    d3=$(extract_gate_date "$gate_log" "S3")
    d4=$(extract_gate_date "$gate_log" "S4")

    s12="-"; s23="-"; s34="-"; total="-"
    [ -n "$d1" ] && [ -n "$d2" ] && s12=$(date_diff "$d1" "$d2")
    [ -n "$d2" ] && [ -n "$d3" ] && s23=$(date_diff "$d2" "$d3")
    [ -n "$d3" ] && [ -n "$d4" ] && s34=$(date_diff "$d3" "$d4")
    [ -n "$d1" ] && [ -n "$d4" ] && total=$(date_diff "$d1" "$d4")

    echo "| $proj_name | ${s12}d | ${s23}d | ${s34}d | ${total}d |"
  done

  echo ""

  # --- Todo 완료율 ---
  echo "## Todo 완료율"
  echo ""
  echo "| Project | Done | Doing | QA | Todo | 완료율 |"
  echo "|---------|:----:|:-----:|:--:|:----:|:------:|"

  for proj_dir in "$WORKSPACE/$PRODUCT_DIR"/*/; do
    [ ! -d "$proj_dir" ] && continue
    proj_name="$(basename "$proj_dir")"
    [ -n "$TARGET_PROJECT" ] && [ "$proj_name" != "$TARGET_PROJECT" ] && continue

    todo_file=$(find "$proj_dir" -maxdepth 1 -name "*todo*.md" -type f 2>/dev/null | head -1 || echo "")
    [ -z "$todo_file" ] && continue

    done_count=$(grep -c "Done" "$todo_file" 2>/dev/null || echo "0")
    doing_count=$(grep -c "Doing" "$todo_file" 2>/dev/null || echo "0")
    qa_count=$(grep -c "QA" "$todo_file" 2>/dev/null || echo "0")
    todo_count=$(grep -c "Todo" "$todo_file" 2>/dev/null || echo "0")
    total_count=$((done_count + doing_count + qa_count + todo_count))

    if [ "$total_count" -gt 0 ]; then
      pct=$((done_count * 100 / total_count))
    else
      pct=0
    fi

    echo "| $proj_name | $done_count | $doing_count | $qa_count | $todo_count | ${pct}% |"
  done

  echo ""
  echo "---"
  echo "*Generated by \`sigil metrics\`*"

} > "$OUTPUT_FILE"

echo -e "${GREEN}=== Metrics report generated ===${NC}"
echo "  $OUTPUT_FILE"
